"""Atlascore: from-scratch multi-agent core for Atlas."""

from .agents._agent import Agent
from .base_types import ToolResult, Usage
from .cancellation import CancellationToken
from .context import AgentContext, ToolApprovalRequest, ToolApprovalResponse
from .llm._base import (
    AuthenticationError,
    BaseChatCompletionClient,
    BaseChatCompletionError,
    InvalidRequestError,
    RateLimitError,
)
from .llm._openai import OpenAIChatCompletionClient
from .memory import (
    BaseMemory,
    FileMemory,
    ListMemory,
    MemoryContent,
    MemoryQueryResult,
)

try:
    from .memory import QdrantMemory
except ImportError:
    QdrantMemory = None  # type: ignore[assignment, misc]
from .messages import (
    AssistantMessage,
    BaseMessage,
    Message,
    MultiModalMessage,
    SystemMessage,
    ToolCallRequest,
    ToolMessage,
    UserMessage,
)
from .middleware import (
    ApprovalMiddleware,
    BaseMiddleware,
    LoggingMiddleware,
    MiddlewareChain,
    MiddlewareContext,
)
from .research_schemas import Citation, Evidence, ResearchBrief, VerificationResult
from .termination import (
    BaseTermination,
    CompositeTermination,
    ExternalTermination,
    MaxMessageTermination,
    TextMentionTermination,
    TimeoutTermination,
    TokenUsageTermination,
)
from .tools._base import ApprovalMode, BaseTool, FunctionTool
from .tools._core_tools import (
    CalculatorTool,
    DateTimeTool,
    JSONParserTool,
    RegexTool,
    TaskStatusTool,
    ThinkTool,
    create_core_tools,
)
from .types import (
    AgentEvent,
    AgentResponse,
    ChatCompletionChunk,
    ChatCompletionResult,
    ErrorEvent,
    ModelCallEvent,
    ModelResponseEvent,
    OrchestrationResponse,
    StopMessage,
    TaskCompleteEvent,
    TaskStartEvent,
    ToolApprovalEvent,
    ToolCallEvent,
    ToolCallResponseEvent,
)
from .workflow import (
    AgentStep,
    BaseStep,
    CheckpointConfig,
    CheckpointSavedEvent,
    CheckpointStore,
    Context,
    Edge,
    EdgeCondition,
    FileCheckpointStore,
    FunctionStep,
    InMemoryCheckpointStore,
    StepExecution,
    StepFailedEvent,
    StepMetadata,
    StepStartedEvent,
    Workflow,
    WorkflowCheckpoint,
    WorkflowCompletedEvent,
    WorkflowEvent,
    WorkflowExecution,
    WorkflowFailedEvent,
    WorkflowMetadata,
    WorkflowRunner,
    WorkflowValidationResult,
)

__version__ = "0.1.0"

__all__ = [
    "Agent",
    "Usage",
    "ToolResult",
    "CancellationToken",
    "AgentContext",
    "ToolApprovalRequest",
    "ToolApprovalResponse",
    "BaseChatCompletionClient",
    "BaseChatCompletionError",
    "AuthenticationError",
    "RateLimitError",
    "InvalidRequestError",
    "OpenAIChatCompletionClient",
    "MemoryContent",
    "MemoryQueryResult",
    "BaseMemory",
    "ListMemory",
    "FileMemory",
    *(["QdrantMemory"] if QdrantMemory is not None else []),
    "BaseMessage",
    "Message",
    "SystemMessage",
    "UserMessage",
    "AssistantMessage",
    "ToolMessage",
    "MultiModalMessage",
    "ToolCallRequest",
    "BaseTool",
    "FunctionTool",
    "ApprovalMode",
    "ThinkTool",
    "CalculatorTool",
    "DateTimeTool",
    "JSONParserTool",
    "RegexTool",
    "TaskStatusTool",
    "create_core_tools",
    "AgentResponse",
    "AgentEvent",
    "ChatCompletionResult",
    "ChatCompletionChunk",
    "TaskStartEvent",
    "TaskCompleteEvent",
    "ModelCallEvent",
    "ModelResponseEvent",
    "ToolCallEvent",
    "ToolCallResponseEvent",
    "ErrorEvent",
    "OrchestrationResponse",
    "StopMessage",
    "BaseTermination",
    "MaxMessageTermination",
    "TokenUsageTermination",
    "TimeoutTermination",
    "TextMentionTermination",
    "ExternalTermination",
    "CompositeTermination",
    "BaseMiddleware",
    "MiddlewareChain",
    "MiddlewareContext",
    "LoggingMiddleware",
    "ApprovalMiddleware",
    "Citation",
    "Evidence",
    "VerificationResult",
    "ResearchBrief",
    "ToolApprovalEvent",
    "Workflow",
    "WorkflowMetadata",
    "WorkflowExecution",
    "WorkflowRunner",
    "WorkflowEvent",
    "WorkflowCompletedEvent",
    "WorkflowFailedEvent",
    "WorkflowValidationResult",
    "WorkflowCheckpoint",
    "CheckpointConfig",
    "CheckpointStore",
    "FileCheckpointStore",
    "InMemoryCheckpointStore",
    "BaseStep",
    "FunctionStep",
    "AgentStep",
    "StepMetadata",
    "StepExecution",
    "StepStartedEvent",
    "StepFailedEvent",
    "CheckpointSavedEvent",
    "Context",
    "Edge",
    "EdgeCondition",
]
