"""Atlascore: from-scratch multi-agent core for Atlas."""

from .agents._agent import Agent
from .agents._computer_use import ComputerUseAgent, PlaywrightWebClient, create_playwright_tools
from .base_types import ToolResult, Usage
from .cancellation import CancellationToken
from .context import AgentContext, ToolApprovalRequest, ToolApprovalResponse
from .llm._base import (
    AuthenticationError,
    BaseChatCompletionClient,
    BaseChatCompletionError,
    InvalidRequestError,
    RateLimitError,
)
from .llm._openai import OpenAIChatCompletionClient
from .memory import (
    BaseMemory,
    FileMemory,
    ListMemory,
    MemoryContent,
    MemoryQueryResult,
)

try:
    from .memory import QdrantMemory
except ImportError:
    QdrantMemory = None  # type: ignore[assignment, misc]
from .eval import (
    BaseEvalJudge,
    CallableTarget,
    CriterionScore,
    Dataset,
    EvalResults,
    EvalRunner,
    EvalScore,
    JudgeResponse,
    LLMEvalJudge,
    ReferenceEvalJudge,
    ResearchPipelineTarget,
    RunTrajectory,
    Target,
    Task,
    TaskResult,
)
from .messages import (
    AssistantMessage,
    BaseMessage,
    Message,
    MultiModalMessage,
    SystemMessage,
    ToolCallRequest,
    ToolMessage,
    UserMessage,
)
from .middleware import (
    ApprovalMiddleware,
    BaseMiddleware,
    LoggingMiddleware,
    MiddlewareChain,
    MiddlewareContext,
)
from .orchestration import (
    AgentSelection,
    AIOrchestrator,
    BaseOrchestrator,
    ExecutionPlan,
    PlanBasedOrchestrator,
    PlanStep,
    RoundRobinOrchestrator,
    StepProgressEvaluation,
)
from .research_schemas import (
    Citation,
    CriticReview,
    Evidence,
    ResearchBrief,
    ResearchPlan,
    ResearchReport,
    SearchOutput,
    SearchResult,
    TriageClassification,
    TriageResult,
    VerificationResult,
)
from .termination import (
    BaseTermination,
    CompositeTermination,
    ExternalTermination,
    MaxMessageTermination,
    TextMentionTermination,
    TimeoutTermination,
    TokenUsageTermination,
)
from .tools._base import ApprovalMode, BaseTool, FunctionTool
from .tools._core_tools import (
    CalculatorTool,
    DateTimeTool,
    JSONParserTool,
    RegexTool,
    TaskStatusTool,
    ThinkTool,
    create_core_tools,
)
from .types import (
    AgentEvent,
    AgentExecutionCompleteEvent,
    AgentExecutionStartEvent,
    AgentResponse,
    AgentSelectionEvent,
    ChatCompletionChunk,
    ChatCompletionResult,
    ErrorEvent,
    ModelCallEvent,
    ModelResponseEvent,
    OrchestrationCompleteEvent,
    OrchestrationEvent,
    OrchestrationResponse,
    OrchestrationStartEvent,
    StopMessage,
    TaskCompleteEvent,
    TaskStartEvent,
    ToolApprovalEvent,
    ToolCallEvent,
    ToolCallResponseEvent,
)
from .workflow import (
    AgentStep,
    BaseStep,
    CheckpointConfig,
    CheckpointSavedEvent,
    CheckpointStore,
    Context,
    Edge,
    EdgeCondition,
    FileCheckpointStore,
    FunctionStep,
    InMemoryCheckpointStore,
    StepExecution,
    StepFailedEvent,
    StepMetadata,
    StepStartedEvent,
    Workflow,
    WorkflowCheckpoint,
    WorkflowCompletedEvent,
    WorkflowEvent,
    WorkflowExecution,
    WorkflowFailedEvent,
    WorkflowMetadata,
    WorkflowRunner,
    WorkflowValidationResult,
)

__version__ = "0.1.0"

__all__ = [
    "Agent",
    "ComputerUseAgent",
    "PlaywrightWebClient",
    "create_playwright_tools",
    "Usage",
    "ToolResult",
    "CancellationToken",
    "AgentContext",
    "ToolApprovalRequest",
    "ToolApprovalResponse",
    "BaseChatCompletionClient",
    "BaseChatCompletionError",
    "AuthenticationError",
    "RateLimitError",
    "InvalidRequestError",
    "OpenAIChatCompletionClient",
    "MemoryContent",
    "MemoryQueryResult",
    "BaseMemory",
    "ListMemory",
    "FileMemory",
    *(["QdrantMemory"] if QdrantMemory is not None else []),
    "BaseMessage",
    "Message",
    "SystemMessage",
    "UserMessage",
    "AssistantMessage",
    "ToolMessage",
    "MultiModalMessage",
    "ToolCallRequest",
    "BaseTool",
    "FunctionTool",
    "ApprovalMode",
    "ThinkTool",
    "CalculatorTool",
    "DateTimeTool",
    "JSONParserTool",
    "RegexTool",
    "TaskStatusTool",
    "create_core_tools",
    "AgentResponse",
    "AgentEvent",
    "ChatCompletionResult",
    "ChatCompletionChunk",
    "TaskStartEvent",
    "TaskCompleteEvent",
    "ModelCallEvent",
    "ModelResponseEvent",
    "ToolCallEvent",
    "ToolCallResponseEvent",
    "ErrorEvent",
    "AgentSelectionEvent",
    "AgentExecutionStartEvent",
    "AgentExecutionCompleteEvent",
    "OrchestrationStartEvent",
    "OrchestrationCompleteEvent",
    "OrchestrationEvent",
    "OrchestrationResponse",
    "StopMessage",
    "BaseTermination",
    "MaxMessageTermination",
    "TokenUsageTermination",
    "TimeoutTermination",
    "TextMentionTermination",
    "ExternalTermination",
    "CompositeTermination",
    "BaseMiddleware",
    "MiddlewareChain",
    "MiddlewareContext",
    "LoggingMiddleware",
    "ApprovalMiddleware",
    "Citation",
    "Evidence",
    "VerificationResult",
    "ResearchBrief",
    "ResearchPlan",
    "ResearchReport",
    "SearchOutput",
    "SearchResult",
    "TriageClassification",
    "TriageResult",
    "CriticReview",
    "ToolApprovalEvent",
    "Workflow",
    "WorkflowMetadata",
    "WorkflowExecution",
    "WorkflowRunner",
    "WorkflowEvent",
    "WorkflowCompletedEvent",
    "WorkflowFailedEvent",
    "WorkflowValidationResult",
    "WorkflowCheckpoint",
    "CheckpointConfig",
    "CheckpointStore",
    "FileCheckpointStore",
    "InMemoryCheckpointStore",
    "BaseStep",
    "FunctionStep",
    "AgentStep",
    "StepMetadata",
    "StepExecution",
    "StepStartedEvent",
    "StepFailedEvent",
    "CheckpointSavedEvent",
    "Context",
    "Edge",
    "EdgeCondition",
    "BaseOrchestrator",
    "RoundRobinOrchestrator",
    "AIOrchestrator",
    "AgentSelection",
    "PlanBasedOrchestrator",
    "ExecutionPlan",
    "PlanStep",
    "StepProgressEvaluation",
    "Dataset",
    "Task",
    "RunTrajectory",
    "EvalScore",
    "EvalResults",
    "TaskResult",
    "EvalRunner",
    "BaseEvalJudge",
    "LLMEvalJudge",
    "ReferenceEvalJudge",
    "CriterionScore",
    "JudgeResponse",
    "Target",
    "CallableTarget",
    "ResearchPipelineTarget",
]
